name: servus_app
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=2.19.4 <4.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  go_router: ^16.0.0
  google_fonts: ^6.2.1
  english_words: ^4.0.0
  provider: ^6.0.0
  flutter_svg: ^2.2.0
  flutter_slidable: ^4.0.0
  table_calendar: ^3.0.9
  image_picker: ^1.0.5
  shared_preferences: ^2.2.2
  mobile_scanner: ^7.0.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_local_notifications: ^16.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/google_logo.svg
    - assets/images/logo.svg
    - assets/images/welcome_illustration.png
    - assets/images/app_logo1080.png
    - assets/images/app_logo.png
    - assets/images/app_logo_android.png
    - assets/images/logo_loading.png
    - assets/images/sem_escalas.svg

flutter_launcher_icons:
  android: true
  ios: true
  image_path_ios: "assets/images/app_logo.png" # caminho para o ícone do aplicativo
  image_path_android: "assets/images/app_logo_android.png" # caminho para o ícone do aplicativo
  adaptive_icon_background: "#4058DB"
  adaptive_icon_foreground: "assets/images/app_logo_android.png"
  remove_alpha_ios: true
  min_sdk_android: 21 # mínimo recomendado para ícones adaptáveis
